version: "3"
services:
  # mysqldb:
  #   container_name: mySql
  #   image: mysql
  #   ports:
  #     - "3307:3306"
  #   environment:
  #     MYSQL_DATABASE: nabd
  #     MYSQL_ROOT_PASSWORD: root
  springboot-app:
    container_name: backend
    image: back:nabdelhayah-latest
    # depends_on:
    #   - mysqldb
    restart: on-failure
    build : .
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mySql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      MYSQL_DATABASE: nabd
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules.yml:/etc/prometheus/rules.yml
    ports:
      - 9090:9090


