name: Node Github CI

on:
  push:
    branches:
      - main
env:
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD  }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@v1.0.3
      if: github.ref == 'refs/heads/main'
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /code/Nabd_project ; git pull
          docker build -t api:nabdelhayah-latest .
          docker stop api || true
          docker rm api || true
          
          docker run --rm --name api  -d \
            -p 8081:8080 \
            -e MYSQL_PASSWORD=${{ env.MYSQL_PASSWORD }} \
            -e MYSQL_PORT=33006 \
            -e MYSQL_DATABASE=nabd \
            -e MYSQL_HOST=172.17.0.1 \
            -e MYSQL_USER=nabd \
            back:nabdelhayah-latest